[project]
name = "documentation"
version = "0.1.0"
description = "Tutorial for MCP Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
]